### ISSUE TITLE
GS rendering is broken on both Windows & WSL

### ISSUE THREAD

**Issue by sylyt62** [ShenhanQian/GaussianAvatars#109]
**On Windows:**
python 3.11 + torch 2.4.1 + cuda 12.4 + nvdiffrast 0.3.3

**On WSL2 (Ubuntu 22.04):**
python 3.11 + torch 2.7.1 + cuda 12.8 + nvdiffrast 0.3.3

---
The render results on windows and wsl are the same:

Offline render results:
<img width="972" height="680" alt="Image" src="https://github.com/user-attachments/assets/1084a5c3-3838-4658-ae9a-8a2e6c26429e" />

Local Viewer:
<img width="946" height="533" alt="Image" src="https://github.com/user-attachments/assets/b374f8bf-61b4-4147-8b8d-44e7226a4b67" />

**Comment by sylyt62** [comment]
I might find the reason. Be sure to use [diff-gaussian-rasterization @ 59f5f77] and [simple-knn @ 44f7642]. Then it works on WSL:

<img width="970" height="572" alt="Image" src="https://github.com/user-attachments/assets/ed21bed5-9060-4cbf-978c-38f8713717a6" />

**Comment by ShenhanQian** [comment]
Thanks for reporting the issue!

I tried to reproduce your setting `python 3.11 + torch 2.7.1 + cuda 12.8 + nvdiffrast 0.3.3`
and got the compilation error:
```
/storage/user/qis/code/tmp/GaussianAvatars/submodules/simple-knn/simple_knn.cu(90): error: identifier "FLT_MAX" is undefined
      me.minn = { FLT_MAX, FLT_MAX, FLT_MAX };
```
which is caused by the old simple-knn version @ 44f7642 not compatible with CUDA >= 12.5  (https://github.com/camenduru/simple-knn/pull/4).

Then, one can either 
1. upgrade simple-knn to newer version to work with CUDA >= 12.5 
2. stay with simple-knn version @ 44f7642 and downgrade to CUDA < 12.5

**I am wondering if you got the buggy rendering with solution 1 and the correct rendering with solution 2?** @sylyt62

**Comment by ShenhanQian** [comment]
To add a bit more context, `diff-gaussian-rasterization @ 59f5f77` and `simple-knn @ 44f7642` are what you get by default with
```shell
git clone https://github.com/ShenhanQian/GaussianAvatars.git --recursive
````

Unfortunately, diff-gaussian-rasterization @ 59f5f77 does not compile with CUDA 12.8 either with similar problems as
```shell
GaussianAvatars/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.h(40): error: identifier "uint32_t" is undefined
      uint32_t* point_offsets;
```
Therefore, a simple choice would be using older CUDA versions such as 11.7 and 12.1 that we have fully tested.

**Comment by sylyt62** [comment]
> Thanks for reporting the issue!
> 
> I tried to reproduce your setting `python 3.11 + torch 2.7.1 + cuda 12.8 + nvdiffrast 0.3.3` and got the compilation error:
> 
> ```
> /storage/user/qis/code/tmp/GaussianAvatars/submodules/simple-knn/simple_knn.cu(90): error: identifier "FLT_MAX" is undefined
>       me.minn = { FLT_MAX, FLT_MAX, FLT_MAX };
> ```
> 
> which is caused by the old simple-knn version @ 44f7642 not compatible with CUDA >= 12.5 ([camenduru/simple-knn#4](https://github.com/camenduru/simple-knn/pull/4)).
> 
> Then, one can either
> 
> 1. upgrade simple-knn to newer version to work with CUDA >= 12.5
> 2. stay with simple-knn version @ 44f7642 and downgrade to CUDA < 12.5
> 
> **I am wondering if you got the buggy rendering with solution 1 and the correct rendering with solution 2?** [@sylyt62](https://github.com/sylyt62)

@ShenhanQian Add a simple line and the compilation should be fine ;)
https://github.com/graphdeco-inria/gaussian-splatting/issues/373#issuecomment-2799856503

**Comment by ShenhanQian** [comment]
Thanks! I see that the compilation problem can be solved with minor adjustments. But I am still wondering in which case one would get the buggy rendering.

diff-gaussian-rasterization @ 59f5f77 is still the latest version

commits after simple-knn @ 44f7642 do not seem to contain huge change of behavior as well.

**Comment by sylyt62** [comment]
> Thanks! I see that the compilation problem can be solved with minor adjustments. But I am still wondering in which case one would get the buggy rendering.
> 
> diff-gaussian-rasterization @ 59f5f77 is still the latest version
> 
> commits after simple-knn @ 44f7642 do not seem to contain huge change of behavior as well.

I'm still working on similar tasks. I will update any findings here if possible. Thanks for your great work, cheers!
